const BREEDS= 'BREEDS';
const BREED_DELETE = 'BREED_DELETE';

const BREEDS_REQUEST = 'BREEDS_REQUEST';
const BREEDS_SUCCESS = 'BREEDS_SUCCESS';
const BREEDS_FAILURE = 'BREEDS_FAILURE';
const BREED_UPDATE = 'BREED_UPDATE'



const types = {
    BREEDS,
    BREEDS_REQUEST,
    BREEDS_FAILURE,
    BREEDS_SUCCESS,
    BREED_DELETE,
    BREED_UPDATE

};

export default types;