const CAT_LIST = 'CAT_LIST';
const CAT = 'CAT'

const CAT_LIST_REQUEST = 'CAT_LIST_REQUEST';
const CAT_LIST_SUCCESS = 'CAT_LIST_SUCCESS';
const CAT_LIST_FAILURE = 'CAT_LIST_FAILURE';

const CAT_REQUEST = 'CAT_REQUEST';
const CAT_SUCCESS = 'CAT_SUCCESS';
const CAT_FAILURE = 'CAT_FAILURE';

const types = {
    CAT_LIST,
    CAT,
    CAT_LIST_REQUEST,
    CAT_LIST_FAILURE,
    CAT_LIST_SUCCESS,
    CAT_REQUEST,
    CAT_SUCCESS,
    CAT_FAILURE
};

export default types;