const IMAGES= 'IMAGES';

const IMAGES_REQUEST= 'IMAGES_REQUEST';
const IMAGES_SUCCESS= 'IMAGES_SUCCESS';
const IMAGES_FAILURE= 'IMAGES_FAILURE';

const IMAGES_PAGES= 'IMAGES_PAGES';

const IMAGE_DELETE= 'IMAGE_DELETE';
const IMAGE_ADD= 'IMAGE_ADD';
const IMAGE_UPDATE= 'IMAGE_UPDATES';


const types = {
    IMAGES,
    IMAGES_REQUEST,
    IMAGES_SUCCESS,
    IMAGES_FAILURE,
    IMAGE_DELETE,
    IMAGES_PAGES,
    IMAGE_ADD,
    IMAGE_UPDATE


};

export default types;