const CATEGORIES= 'CATEGORIES';

const CATEGORIES_REQUEST= 'CATEGORIES_REQUEST';
const CATEGORIES_SUCCESS= 'CATEGORIES_SUCCESS';
const CATEGORIES_FAILURE= 'CATEGORIES_FAILURE';


const types = {
    CATEGORIES,
    CATEGORIES_REQUEST,
    CATEGORIES_SUCCESS,
    CATEGORIES_FAILURE



};

export default types;