const USER_LIST = 'USER_LIST';
const USER = 'USER'

const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
const USER_LIST_FAILURE = 'USER_LIST_FAILURE';

const USER_REQUEST = 'USER_REQUEST';
const USER_SUCCESS = 'USER_SUCCESS';
const USER_FAILURE = 'USER_FAILURE';

const types = {
    USER_LIST,
    USER,
    USER_LIST_REQUEST,
    USER_LIST_FAILURE,
    USER_LIST_SUCCESS,
    USER_REQUEST,
    USER_SUCCESS,
    USER_FAILURE
};

export default types;